application: cute-pic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rest/.*
  script: main.application

- url: (.*)/add
  static_files: app\1/index.html
  upload: app.js

- url: (.*)
  static_files: app\1
  upload: app.js



