application: cute-pic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rest/.*
  script: main.application

- url: (.*)/add
  static_files: app\1/index.html
  upload: app.js

- url: /(.*\.css)
  mime_type: text/css
  static_files: app/\1
  upload: app/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: app/\1
  upload: app/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: app/\1
  upload: app/(.*\.js)



